### ISSUE TITLE
Parse error: Missing ':' when using #comments in .pa.yaml source files

### ISSUE THREAD

**Issue by scottdurow** [microsoft/PowerApps-Language-Tooling#115]
The following code gives the error `Error   PA3003: Parse error: Missing ':'. If this is a multiline property, use | at Screen1.pa.yaml:2,18-2,18`

```
Screen1 As screen:
    # Some comment
    sldSlider As slider:
        # Another comment
        Max: =sldSlider.Width
       ...
```

but this code packs ok:
```
Screen1 As screen:
# Some comment
    sldSlider As slider:
        # Another comment
        Max: =sldSlider.Width

```
When I unpack after a pack with comments - the pa.yaml is missing all the detal after the comment and is just:
```
Screen1 As screen:
```

Are yaml comments supported in pa.yaml files?

**Comment by MikeStall** [comment]
We *do not support Yaml comments* in the .pa.yaml file. This is because we they would get dropped during a round trip. 
We do support PowerApps comments in the formulas (use // ) 

We should be giving parser errors in the cases above to explicitly warn which parts of Yaml are not in the supported subset. 

We're capturing the docs for this here:
https://github.com/microsoft/PowerApps-Language-Tooling/blob/master/docs/YAMLFileFormat.md#yaml-comments

**Comment by scottdurow** [comment]
Rather than block the pack - could comments be allowed but a warning emitted to indicate that they won't be retained if you round trip - I can think of situations where comments would be useful in code-gen type scenarios.

**Comment by MikeStall** [comment]
We'll allow comments on their own line.  
But we still reject yaml comments on a line with other formulas - because it's too easy that the intention was actually a formula and we're trying to protect against confusion (and against the formulas being accidentally interpreted as yaml comments and stripped ) 

```
Screen1 As screen:
    # A comment    <-- this yaml comment is ok 
    FillColor: = # FF00CC   <-- this is an error.  Yaml comment not allowed,     
```

We'll give a warning now like: 

```
Pack: D:\dev\pa2\Samples\FullDemo\Weather\MyWeather_src --> D:\dev\pa2\Samples\FullDemo\Weather\temp.msapp
Warning PA2010: Yaml comments don't roundtrip. at Screen1.pa.yaml:14,1-14,1
0 errors, 1 warnings.
```
