### ISSUE TITLE
Make AppCheckerResult.sarif available

### ISSUE THREAD

**Issue by devkeydet** [microsoft/PowerApps-Language-Tooling#121]
#72 moved AppCheckerResult.sarif to Entropy file.  We want to use this Azure DevOps extension:
https://marketplace.visualstudio.com/items?itemName=sariftools.scans
...to be able to review app checker results during the Pull Request process.  The extension makes the contents of *.sarif files readable on the individual build page in Azure DevOps by adding a Scans tab.  Want to make it part of our process to review the Scans tab as part of a PR.  We require builds when PRs are submitted or when the source branch for the PR is updated.  To use the extension for this review process, the extension requires one can add grab a *.sarif file and publish it to an Azure DevOps artifact.

**Comment by MikeStall** [comment]
We have some forces pushing it into Entropy:
	
1. No noisy diffs -  but sarif is a noisy file (I recall there were even timestamps in it) .  We actually had #72 to move it to entropy.
2. We need clear PR / Merge guidance.  Right now, we tell them to blow away checksum,entropy in case of a merge conflict. 

But this issue makes the case for having it in its own file. 

Splitting into its own file may also help with large files (#94). 

Open question - should we / can we normalize the sarif json? 

Maybe the fix is to have a dedicated folder where all files in the folder have "overwrite on merge" semantics. Entropy, checksum are obvious cases, and sarif may be another case too.

**Comment by devkeydet** [comment]
Normalizing the sarif json would be nice, but not necessary, since in our scenario we don't anticipate people doing diffs on the sarif json.  It's really just a way for us to use the fact that the sarif json is there and surface the results in a more human readable format than looking at json files.  Ideally, the sarif file wouldn't actually be something we commit to source control.  Instead something we can generate during a build and review.

**Comment by MikeStall** [comment]
The challenge is that we also want to reduce noisy diffs - multiple exports of the same msapp shouldn't produce diffs in source control.  Non-canonical json (such as property ordering) can be noisy.

**Comment by devkeydet** [comment]
As long as the sarif file is still valid sarif, then I'm happy.  The AzDO extension references this:
https://github.com/microsoft/sarif-web-component
and this:
https://sarifweb.azurewebsites.net/
If you can reduce noisy diffs wall not impacting it as being valid sarif, I'm all for it!
