### ISSUE TITLE
PublishOrderIndex is a volatile diff after unrelated changes in studio

### ISSUE THREAD

**Issue by lesaltzm** [microsoft/PowerApps-Language-Tooling#135]

**Comment by lesaltzm** [comment]
PublishOrderIndex is an ordering of the controls

**Comment by MikeStall** [comment]
Our findings: PublishOrderIndex  is used to establish a tab-ordering (for accessibility) when the app is running. 

What we have here is a new class of data: _values that can only be computed in the designer_. 

Each control has a PublishOrderIndex, which means adding 1 control to a screen could change the index of every other control and produce noisy diffs.  We already use the serialization order to represent the Z index.  

It's computed automatically based on the X,Y,Z _values_ of _all_ the controls on the page. Values are inherently volatile, (ie, if they're a formula dependent on a data source). We can only evaluate formulas in the client - so we can't even emulate the logic during pack/unpack.  (This design choice should be revisited, but that's a product change )

This means that the index can change when:

- adding a new control 
- moving an existing control (this changes the X,Y values)
- X,Y could even be formulas (which could in turn depend on other formulas, data sources, etc).  So this could be a noisy diff even if maker doesn't change anything but if the formula value changes. 

This is inherently volatile. 

Now we could just include this in entropy so that they round-trip. 
But there are still noisy diffs here, so we still have a challenge with merging pull requests.

**Comment by scottdurow** [comment]
The end goal here is to make merging easy - if we had it in entropy I can imagine that packing would fail after a merge because we don't do merges on entropy files?

**Comment by scottdurow** [comment]
> but it would be rebuilt on next load/save through studio again.

Does this mean that if PublishOrderIndex is in entropy - then merges of changes where controls move x,y will be ok?

**Comment by MikeStall** [comment]
@scottdurow  - our guidance on entropy is that it can be deleted in case of a merge.  Entropy is all the "noisy" - but not essential 
 - stuff like timestamps , It's required to faithfully round trip during pack/unpack.
 

> If two makers add controls to an app such that they don't impact each other - we should be able to merge those two branches? 

Yes! More generally - _if changes don't intrinsically conflict, they should be mergable_.
