### ISSUE TITLE
Working with the unicode screen names

### ISSUE THREAD

**Issue by vkusher** [microsoft/PowerApps-Language-Tooling#187]
The tool escapes all unicode chars and makes file's name unreadble.
The code also crashes when there is a "/" char in the screen's name
Consider to change the **DontEscapeChar** method inside of the **Utilities.cs**
to :
```
private static readonly List<char> invalidChars = Path.GetInvalidFileNameChars().ToList();

private static bool DontEscapeChar(char ch)
{
    return !invalidChars.Contains(ch);
}
```

**Comment by MikeStall** [comment]
Are you on the latest builds? ("FormatVersion": "0.20", in the CanvasManifest.json). 

I just tried an app with a /, and it escapes it as  `Screen%2f1.fx.yaml`  
If it reproes on latest builds, can you share your msapp with us to repro?

One challenge for escaping is that we need to be cross-platform - the files may get unpacked on one OS, checked into git, and then used in another OS. So we can't use Path.GetInvalidFileNameChars.

**Comment by vkusher** [comment]
You're right, the issue related to the lenght of the screen's name.

**Comment by MikeStall** [comment]
How long is it? Can you share the screen's (unescaped) name here?

**Comment by vkusher** [comment]
I think the problem appears when screen's name is greater then 40 unicode characters.
As an example, take this name:
одиндваодиндваодиндваодиндваодиндваодинд

**Comment by MikeStall** [comment]
There are 2 issues here:
1. Long path names. Windows has a limit of MAX_PATH (260) characters for the full filename.  There may be some things to get around this. https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#win32-file-namespaces
2. Better handling of unicode. Do we escape to aggressively?  Escaping hits the first issue because escaping makes the path longer (a single high unicode char becomes 5 escape chars).

**Comment by MikeStall** [comment]
We actually have more flexibility here for the yaml file name because the control's name is still inside the yaml contents. So the yaml file name is not needed to re-pack and get the control name. This means we could do something like truncate for long names, and add a mini hash to avoid collisions (use hash, not incrementing number)

**Comment by MikeStall** [comment]
Adding Breaking tag since if we change the file encoding, that could be breaking.
