### ISSUE TITLE
Warning PA2001 on unpack of package

### ISSUE THREAD

**Issue by psik-sh** [microsoft/PowerApps-Language-Tooling#192]
Hi. When trying to unpack a package, I get this error. Since the error isn't more descriptive, I can e-mail the msapp in question.

**Comment by psik-sh** [comment]
The app in question is an app that has been in development for a long time, so I thought that was the reason the unpack didn't work properly. However, I just tried to unpack a much simpler app and an app I just created with only a single control. Both of these also failed the unpack with the same error.

**Comment by lesaltzm** [comment]
Thanks @psik-sh. Can you send the apps to lesaltzm (at) microsoft.com?

**Comment by LaelLeeH** [comment]
Hi,
Also a noob here. I think I am getting the same error as @psik-sh 

Warning PA2001: Checksum mismatch. Checksum doesn't match on extract.
0 errors, 1 warnings.

When I initially ran the unpack it complained about a chksum mismatch on a table which I had removed from my Azure SQL DB and from my app, months back. So I recreated the table in SQL using its original name, imported it back into my app, saved, published and recreated the msapp file,  and then tried the unpack again. Since then I am no longer getting table error, but now get the above error. Not sure if it is still related to the original table chksum mismatch error.
The table which it complained about is no longer used in my app at all, so not sure why it is still referencing it. Hope this info helps and we can get to the root cause.
Regards
Lael

**Comment by LaelLeeH** [comment]
I see it did unpack the app, so can I just ignore the warning??

**Comment by lesaltzm** [comment]
Hi folks! This is just a Debug warning, it has no impact on the actual project. 

For people facing this issue, if you build the project with `./build ci -c Release` and run the project from `\bin\Release\PASopa\PASopa.exe`, you shouldn't see this warning. If you still are seeing PA2001 after doing that, please create a new issue.
