### ISSUE TITLE
ParentIndex property random?

### ISSUE THREAD

**Issue by m3ngi3** [microsoft/PowerApps-Language-Tooling#193]
I am just a noob when it comes to developing so please forgive me if this not worth adding to the GitHub as an issue.

My situation:
I have a Power App connecting to SQL database. I duplicated the Power App for DEV-purposes in studio and reconnected to duplicate Flows as well as the SQL Connections to a DEV-Gateway connecting to a DEV-database (on same machine as PROD-database but nevertheless a different database). 

My expectation:
When comparing the unpacked .msapp files, the screen definitions show a different ParentIndex number.
![image](https://user-images.githubusercontent.com/47530580/112815378-88301c00-9080-11eb-9d82-f16fe2837d1d.png)
Why is this? Is this expected behavior after only changing connections and not any of the screens/components/controls?

**Comment by jt000** [comment]
@m3ngi3 - This occurs due to the nature of the way connectors are stored on the backend. I don't think we'd be able to address this easily in the canvas pack\unpack and is (I believe) expected given changes to the connectors are changing. If this continues to cause you issues, please re-open and we can take a deeper look.
