### ISSUE TITLE
Validate custom property names on components

### ISSUE THREAD

**Issue by johnelsbree** [microsoft/PowerApps-Language-Tooling#281]
Custom properties on components have some naming restrictions:

- Characters must be only letters, digits, or underscores
- No duplication of existing property names
- Some names are reserved: AlignInContainer, FillPortions, LayoutMinWidth, LayoutMaxWidth

Language tooling should enforce these restrictions.

**Comment by jt000** [comment]
Thank you for the suggestion @johnelsbree. We're actually intending to go the opposite direction and _remove_ a lot of the business logic out of the canvas pack\unpack. The eventual dream is that the YAML formats are used natively on the server within the MSApp & the canvas pack\unpack purely becomes solely a zip\unzip tool with very little business logic. It would be up to the server to provide validation on the MSApp rather than the canvas pack\unpack.

Additionally, there is a distinction that we need to make in the canvas pack\unpack tool between a "well-formed" MSApp that is unable to run & an "invalid" MSApp. The more validation we attempt to enforce on the client, the more we prevent a "well-formed", but un-runnable MSApp to be further edited in another tool like make.powerapps.com. 

That said, one day we probably do need to consider a way to validate a MSApp without publishing, but I don't think this tool is the one that will provide that functionality.
