### ISSUE TITLE
Unpack results in missing multiple artifacts

### ISSUE THREAD

**Issue by NavneetThekkumpat** [microsoft/PowerApps-Language-Tooling#370]
**Describe the bug**

Same issue here with pac canvas unpack.

PowerPlatform CLI version 1.12.2 resulted in:
Error PA3011: Roundtrip validation on unpack failed. This is always a bug, please file an issue at https://github.com/microsoft/PowerApps-Language-Tooling

but at least the unpack result seemed complete and valid. Now version 1.13.4 results in:
Sorry, the app encountered a non recoverable error and will need to terminate. The exception details have been captured and will be forwarded to the development team, if telemetry has been enabled. Exception Id: 6d065f94-4f4a-41e3-8c5d-9fe6986d5228, Exception Type: System.ArgumentException

and the result is missing multiple artifacts in Connections, DataSources, TableDefinitions as well as AppInsightsKey.json, CanvasManifest.json and ComponentReferences.json in the root.

**To Reproduce**

1. pac canvas unpack.

**Comment by NavneetThekkumpat** [comment]
@[maskati](https://github.com/maskati) : can you mail me your msapp as a repo, at nthekkumpat at microsoft dot com?

**Comment by maskati** [comment]
@NavneetThekkumpat sorry I missed your message. Unfortunately I cannot share the msapp directly without going through an approval process. However I can confirm that the issue is resolved by custom building from [81aba52](https://github.com/microsoft/PowerApps-Language-Tooling/tree/81aba52dd3161dc89dc065341824d0375a2ca633) and unpacking using pasopa.exe.

**Comment by NavneetThekkumpat** [comment]
@maskati Thank you for confirming the issue is resolved and hence closing this issue.
