### ISSUE TITLE
Frozen app in PowerApp Studio, in edit mode

### ISSUE THREAD

**Issue by gbystron** [microsoft/PowerApps-Language-Tooling#405]
Hi,

Please see attached the description of the issue that I'm encountering (step by step what I'm doing, with printscreens)
The problem is with themes.json file, as when I replace it with default (from blank app) it's working without any issue
[Frozen App description.docx](https://github.com/microsoft/PowerApps-Language-Tooling/files/8661005/Frozen.App.description.docx)

![image](https://user-images.githubusercontent.com/105284030/167614817-a391533e-892a-4443-b62b-cd193b4ce8ed.png)

Please note that I've already tried to create a ticket through PowerApps Admin Support (TrackingID#2204200050000590) and they rerouted me to Github - they should have a video of a call where I tried to show my issue

Also I have an error when unpacking. It seems that my component is the problem - when removed, there is no error
![image](https://user-images.githubusercontent.com/105284030/167614318-025a3b77-4cc7-462c-9f2f-4dcc84649bc4.png)

MSAPP theme template attached here

[in-SE.Theme.v2-20220510_GitHub11.msapp.zip](https://github.com/microsoft/PowerApps-Language-Tooling/files/8660996/in-SE.Theme.v2-20220510_GitHub11.msapp.zip)

**Comment by gbystron** [comment]
@landonarogers I use PASopa in powershell/cmd and I think I have the latest version 0.24? You talking about PA3011 error? Worse error is that I have frozen app in PowerApps studio and those two issues are different

**Comment by landonarogers** [comment]
Gotcha; you might want to try running the PAC CLI instead of PASopa. That should give you the new messages and/or fix the issue.

**Comment by landonarogers** [comment]
No problem! So the first part of the command is correct:

'pac canvas unpack'

However, you also have to use the `--sources` flag and the `--msapp` flag.
After the `--sources` flag, put the path to where you want the unpacked app to go. This has to be an empty folder and/or a folder that does not already exist (but will be created from this command, after it runs).

After the `--msapp` flag, you need to include the path to the msapp you are currently attempting to unpack.

So, in the end, your command should look something like this:

`pac canvas unpack --sources "C:\intended\destination\currently\nonexistent\folder" --msapp "C:\path\to\msapp.msapp"`

**Comment by gbystron** [comment]
In ms docs they didn't mention about source and in PASopa you don't need to mention source.
So I unpack it without any errors. Is pac better then PASopa then? What about frozen app, are you also gonna look at it?
Not sure how this Github support or/and Github in general working

**Comment by landonarogers** [comment]
@gbystron For your frozen app issue; did you change your Themes.json file manually? And if so, how did you change it?

**Comment by gbystron** [comment]
I did manually. I wanted to create my own theme. Unpack msapp, edit
themes.json file in VSCode, pack, open in power apps. For few weeks it was
working fine. As there is a way to edit it in power apps without frozen
app, I don't know exactly at what time I did something wrong in
themes.json. However I didn't have any error messages when packing msapp,
but I did it with PASopa. Tomorrow I'll try to pack with pac, maybe some
error appears

**Comment by gbystron** [comment]
There is no errors using pac

**Comment by landonarogers** [comment]
So, .json files need to be handled with great care. Editing them directly comes with a risk of causing unexpected behavior in PowerApps Studio, because it is not hardened for anything it does not expect. Unfortunately, we're unable to assist with any issues caused by editing .json files directly, at the moment. I apologize for the inconvenience!

However, there are two possible things you could do to remedy your issue. rollback to a previous version before the latest change and extract the themes.json from there, or pull the themes.json from a new file
1. Rollback to a previous version, if you can, before you noticed this issue occurring, and then use the themes.json from that version.
2. Pull and replace the themes.json file using the themes.json from a new PowerApps app exported from Studio.

**Comment by landonarogers** [comment]
So, .json files need to be handled with great care. Editing them directly comes with a risk of causing unexpected behavior in PowerApps Studio, because it is not hardened for anything it does not expect. Unfortunately, we're unable to assist with any issues caused by editing .json files directly, at the moment. I apologize for the inconvenience!

However, there are two possible things you could do to remedy your issue:
1. Rollback to a previous version, if you can, before you noticed this issue occurring, and then use the themes.json from that version.
2. Pull and replace the themes.json file using the themes.json from a new PowerApps app exported from Studio.

It's best to handle things directly in Studio, however if you do want to edit files directly, take extra caution.

**Comment by gbystron** [comment]
Unfortunately, I can't handle themes directly in Studio due to company policy, I don't have some admin privileges to use CoE pack. There is my only way to create my own theme

I've been trying to resolve it by myself for the last few days and it seems that I found the root of the issue. Turnout that there is a required property in 'palette' in themes.json: 'PrimaryColor1', once I restored this property, my MSAPP is working fine. Is there a way you can confirm that PowerApps studio required property 'PrimaryColor1' or are there any other properties required? Maybe some kind of check could be added to PASopa or PAC

I would really appreciate if you could help me with the below questions or redirect where I can ask them:
Is there any guide for creating your own theme, what can (can't) you do? There are 27 different Label styles (max 10 used), can I delete them?
What type of 'command' can I use in theme.json, I mean commands like %CONTROL.ID%.Value or %BorderStyle.RESERVED%.Solid. Is there a list maybe?
