### ISSUE TITLE
Connections.json

### ISSUE THREAD

**Issue by mitchellromanuik** [microsoft/PowerApps-Language-Tooling#432]
I have a few questions on the purpose of Connections.json.

PASopa.exe doesnt seem to consider this file when packing up the canvas application. 

We have been using DevOp Pipelines to Automate our build processes across environments and tenants as well. The pipeline works great with using solutions, connection references, and environment variables. 

However! The only issue (that hasnt been built out by Microsoft yet) is the SQL Server AAD Authentication (connection reference/environment variable). 

Within DataSources/* and Connections.json files for SQL Tables/Connection. We can see the server,db however when we modify this to point to a different db within the same server. PASopa does not mention the checksum for Connections.json
When importing the PowerApp still points to the old version. Which makes me wonder if this is a Protected file from Microsoft on server side. If we add say another table manually, the Application after import recognizes the new datasource however it says appDataSourceConfig.

We have also tried deleting Entropy.json, Connections.json to see if we could force the app (on initial bootup) to reconfigure itself to pull these values in.

It just seems strange that if we completely remove all references to the old database, package, and import. Microsoft is able to revert back to old values which makes me wonder if Microsoft is Caching and overriding this file (connections.json)

Related #259, #216

**Comment by tomjschneider** [comment]
@mitchellromanuik , I'll do my best to answer this and provide some general information. If you have a specific example of the change you're making that might help me to provide more detailed feedback.

My understanding of the Connections.json and how it works is that it holds reference information to a Power Platform Connection. Ultimately, that Power Platform Connection is what determines the link between your Power App and the Data Source. Changing the data within the Connections.json or related Data Source file may have some impact on the information shown, but if it is still pointing to the same Power Platform Connection, it will continue to resolve to that Connection.

For example, if I had the following Connections.json:
```json
  {
    "e771971d-7763-4c4d-b0d1-e88649d6c2c6": {
      "connectionParameters": {
        "database": "example-db",
        "privacySetting": "None",
        "server": "example-server.com"
      },
      "connectionRef": {
        "authenticationType": "sqlAuthentication",
        "displayName": "SQL Server",
        "iconUri": "https://example.com/icon.png",
        "id": "/providers/microsoft.powerapps/apis/shared_sql",
        "sharedConnectionId": "/providers/microsoft.powerapps/apis/shared_sql/connections/3b10ee7359694a4fa2d7b45fd7761d51"
      },
      "datasets": {
        "example-server.com,example-db": {
          "dataSources": {
            "TestTable1": {
              "tableName": "[dbo].[TestTable1]"
            }
          }
        }
      },
      "dataSources": [
        "TestTable1"
      ],
      "dependencies": {},
      "dependents": [],
      "id": "e771971d-7763-4c4d-b0d1-e88649d6c2c6"
    }
  }
```
I can change the `connectionParameters.database` and `connectionParameters.server` values, or the underlying dataset, but when this Power App is opened the Connection established is determined by the reference to the Connection that exists within the Power Platform (in this case, the `connectionRef.sharedConnectionId`.)

I'm not particularly familiar with SQL Database Connections, so perhaps there is a difference in the expected behavior, but I believe that the best course of action would be to avoid modifying the Connections.json information. As it exists today, this file is meant to preserve Connection information during the pack/unpack process and not for manually establishing connections in offline editing.

**Comment by tomjschneider** [comment]
Closing this for now - please feel free to re-open if you have any additional questions or concerns.
