### ISSUE TITLE
PA3014: DataSources Roundtrip Failure

### ISSUE THREAD

**Issue by haroldbk** [microsoft/PowerApps-Language-Tooling#469]
- [ ] Please attach a sample .msapp to this Issue which demonstrates the issue you are experiencing. *(Please do not attach any file which may contain sensitive personal or company data.)*

**Describe the bug**

unable to unpack an msapp file when using the Power Platform tools in Visual Studio Code

**To Reproduce**

Ran this command 
pac canvas unpack --msapp ElaineF.msapp --sources .\src

This is a partial listing of the errors and the message 
Error   PA3014: Property Added: DataSources[44].NativeCDSDataSourceInfoNameMapping.yomilastname
Error   PA3014: Property Added: DataSources[44].NativeCDSDataSourceInfoNameMapping.yomimiddlename
Error   PA3014: Property Added: DataSources[45].Data
Error   PA3014: Property Added: DataSources[45].OrderedColumnNames
Error   PA3014: Property Added: DataSources[45].OriginalName
Error   PA3014: Property Added: DataSources[45].OriginalSchema
Error   PA3014: Property Added: DataSources[45].Schema
Error   PA3014: Property Added: DataSources[46].ApiId
Error   PA3014: Property Added: DataSources[46].FlowNameId
Error   PA3014: Property Added: DataSources[46].ServiceKind
Error   PA3014: Property Added: DataSources[46].WorkflowEntityId
Error   PA3011: Roundtrip validation on unpack failed.
You have found a bug; this is not a specific bug, rather an indicator that some bug has been encountered.
Please open an issue and log the entirety of this error log at https://github.com/microsoft/PowerApps-Language-Tooling

**Comment by landonarogers** [comment]
Hey, there! Could you attach a sample app that displays this issue, if it doesn't contain any sensitive personal/company data?

**Comment by PatrickMichaelKriegler** [comment]
We are facing what looks to be a similar issue. Only that we have "PA3015: Property Removed" errors. When we roll back the canvas app to a previous version it unpacks just fine. 

After changing Display name on a couple of dataverse fields of our datasourse and then made the necessary minor adjustment in the canvas app where a couple of formulas references these dataverse fields so they reference with the new name instead of the old and we export and unpack the app with these changes we run into the error.. We've tried removing / re-adding and refreshing the dataverse datasource in the canvas app as a workaround but havent been able to find anything let lets us work around it yet. 

I will see if we can et permission to share our app as an example if haroldbk is unable to share.

**Comment by NavneetThekkumpat** [comment]
@haroldbk @mike-ashling : Thank you for the error logs. If possible, please send the app to paadvmakers AT microsoft DOT com and we'll have a look.

**Comment by PatrickMichaelKriegler** [comment]
I have checked and unfortunately am not allowed to share our msapp files.

**Comment by landonarogers** [comment]
Hey, @PatrickMichaelKriegler and @mike-ashling ! It appears that your error could potentially be different, since the error message is not the same. I've created a new issue here: https://github.com/microsoft/PowerApps-Language-Tooling/issues/475 . No worries on not being able to share additional information, we're still investigating this regardless! However, if you do happen change your mind, emailing `paadvmakers AT microsoft DOT com` with additional information/context, referencing this new issue, would help expedite this. However, we completely understand either way! Thank you for your patience, and thanks for reaching out!

**Comment by landonarogers** [comment]
@haroldbk For your issue, are you able to send us an msapp at `paadvmakers AT microsoft DOT com`? This would help us greatly! If not, no worries; we're still looking into this. Thank you!

**Comment by akshar2401** [comment]
Pr linked with this issue got merged recently and would ultimately fix this issue. The fix should be shipped in the next release of PAC CLI

**Comment by akshar2401** [comment]
This has been shipped with the last version of PAC CLI
