### ISSUE TITLE
Error: Error   PA3007: *APP* is corrupted. Duplicate Control Unique Ids

### ISSUE THREAD

**Issue by gavrielsl** [microsoft/PowerApps-Language-Tooling#492]
When i pack the app source file i get the message

Error: Error   PA3007: MsApp is corrupted. Duplicate Control Unique Ids

How can i find the duplication controle ?

**Comment by tomjschneider** [comment]
@gavrielsl Are you getting this just through packing and unpacking, or are you modifying the source files before packing?

If it is just through packing/unpacking, and you can send me your .msapp, I can find the duplicate control ID for you (tschneider AT microsoft DOT com). Otherwise, you'd need to search the controls for the unique ID manually, or build this project locally and run it against your source so you can set a breakpoint.

I'll look into updating our error messaging here to make it clearer in the future.
